# Week 1 · Day 1 — Python Foundations
**Date:** 2025-11-03

**Goals**
- Understand variables, basic data types, and expressions.
- Practice `input()`/`print()` and type conversion.
- Follow PEP 8 conventions and write clear docstrings.
- Push changes to GitHub.

> Tip: Run cells with **Shift+Enter** in VS Code.


# 1. Concepts Recap

## 📘 Chapter 1 – Why We Program

### 1.1 Why We Program
- **Core question:** “What do we want the computer to do next?”  
- Programming acts as an **intermediary** between the user and the hardware.  
- A **program** is a stored sequence of instructions.  
- Computers don’t handle errors on their own — they follow exactly what we tell them.  
- A **syntax error** means Python doesn’t understand the instruction.

### 1.2 Hardware Overview
*(Skipped – already familiar with hardware basics.)*

### 1.3 Python as a Language
- Python was designed to be a **first, easy-to-read language**.  
- Combines **simplicity** with **real-world power**.  
- If you see a **syntax error**, Python is “lost” — your structure or spelling is off.

### 1.4 Paragraphs of Code
- **Chevron prompt (`>>>`)** = Python waiting for the next instruction.  
- **Assignment statement:** `x = 1`  
- **Expression:** `x = x + 1`  
- Python code has:  
  - **Vocabulary:** commands & keywords  
  - **Sentence structure:** syntax / indentation  
  - **Story structure:** overall logic & flow  
- **Reserved words** cannot be used as variable names.  
- A **line** = a sentence; a **set of lines** = a paragraph (script).  
- For short tests → use the **interactive shell**.  
- For real programs → use a **script file (`.py`)** in an editor like VS Code.  
- **Program flow:**  
  - **Sequential:** normal top-to-bottom execution  
  - **Conditional:** executes only if a condition is true  
  - **Loop:** repeats steps using an *iteration variable* that changes each cycle  

---

## 📘 Chapter 2 – Variables and Expressions

### 2.1 Expressions (Part 1)
- **Constants** are fixed values such as numbers, letters, or strings.  
- **String constants** use single (`'`) or double (`"`) quotes.  
- **Variables** are named locations in memory where data is stored and later retrieved.  
- The **programmer** chooses the variable name.  

**Naming rules:**
- Must start with a letter or underscore (`_`).  
- May contain letters, numbers, and underscores.  
- Case-sensitive (`age` ≠ `Age`).  
- Avoid starting names with underscores — Python often reserves these internally.  
- Use **mnemonic, meaningful names** to make code readable.  

**Assignment statement:**
```python
x = 5
y = x + 2
```
- The **expression** on the right is evaluated first, then its result is stored in the variable on the left.

---

### 2.2 Expressions (Part 2)
- **Operators** perform mathematical or logical actions:  
  `+` addition | `-` subtraction | `*` multiplication | `/` division | `**` exponent | `%` remainder (modulo)

**Operator precedence (highest → lowest):**
1. Parentheses `()`  
2. Exponentiation `**`  
3. Multiplication / Division / Modulo  
4. Addition / Subtraction  
➡ Evaluated **left → right** within the same level.

**Examples:**
```python
x = 10
y = 3
print(x + y)   # 13
print(x ** y)  # 1000
print(x % y)   # 1
```

**Data types:**
- `int` – whole numbers (`1`, `23`, `1771`)  
- `float` – decimal numbers (`1.1`, `2.34`, `14.0`)

**Mixed operations:**
- Combining `int` and `float` → result is `float`.  
- `/` always returns a float in Python 3.

**Type conversion:**
```python
int("42")      # string → integer  
float("3.14")  # string → float  
str(42)        # integer → string
```

**Illegal operations:**
- Some combinations don’t make sense, e.g. `1 + "two"` → `TypeError`.

**Check a variable’s type:**
```python
x = 3.14
print(type(x))  # <class 'float'>
```

**User input:**
```python
hours = int(input("Enter hours: "))
rate = float(input("Enter rate: "))
pay = hours * rate
print(pay)
```
- `input()` always returns a **string**, so cast it before arithmetic.

---

### 2.3 Expressions (Part 3)
- **Comments** start with `#` and are ignored by Python.  
- Use them to:  
  - Describe what a code block does.  
  - Document logic for future reference.  
  - Temporarily disable a line of code.  
```python
# This calculates weekly pay
pay = hours * rate
```
---

In [4]:
name = input("Enter your name")
print("Hello", name)

Hello sarah


In [5]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")
pay = float(hrs) * float(rate)
print("Pay:",pay)

Pay: 96.25


In [ ]:
"""
Simple Greeting Script
Author: Nicky Rongen
Purpose: Demonstrate input, type conversion, f-strings, and basic arithmetic.
PEP 8: variables_are_snake_case; functions + docstrings; 79-char lines.
"""
def next_year_age(age: int) -> int:
    """Return the age next year.

    Args:
        age (int): Current age in whole years.

    Returns:
        int: Age one year from now.
    """
    return age + 1


def main() -> None:
    """Ask the user for their name and age, then print a message."""
    name = input("What is your name? ")
    # Defensive parsing: handle non-integers gracefully
    try:
        age = int(input("How old are you? "))
    except ValueError as exc:
        print("Please enter your age as a whole number.")
        raise exc

    print(f"Hello, {name}!")
    print(f"Next year you will be {next_year_age(age)} years old.")


if __name__ == "__main__":
    main()


Hello, Nicky!
Next year you will be 34 years old.


### 🔧 Adaptation Challenge
**Modify the script to:**
1. Compute and display your birth year.
2. If today is your birthday (or if you choose a date), print a special message.
3. Validate that age is between 0 and 120; otherwise, show an error and ask again.


## 2. Data Types & Casting — Examples
Use the cell below to experiment with `type()`, `int()`, `float()`, `str()`, and `bool()`.
Explain *why* each conversion works or fails.


In [4]:
# Play with types here
values = [42, 3.14, True, "123", "hello", "3.14"]
for v in values:
    print(v, type(v))

# Conversions
print(int("123"))         # ok
print(float("3.14"))      # ok
print(str(42))            # ok

# What happens here?
print(int("hello"))     # Uncomment and run—why does this raise a ValueError?
# print(bool(""))         # False
# print(bool("0"))        # True (non-empty strings are True)


42 <class 'int'>
3.14 <class 'float'>
True <class 'bool'>
123 <class 'str'>
hello <class 'str'>
3.14 <class 'str'>
123
3.14
42


ValueError: invalid literal for int() with base 10: 'hello'

### 🔍 Explanation

- `int("123")` → works because `"123"` is numeric text that can be turned into an integer.  
- `float("3.14")` → works because `"3.14"` is valid decimal text.  
- `str(42)` → always works; any object can be represented as a string.  
- `int("hello")` → ❌ raises a **ValueError** because `"hello"` isn’t numeric.  
- `bool("")` → `False`, because empty strings are considered *falsy*.  
- `bool("0")` → `True`, because any *non-empty* string is truthy.  

## 3. Style Checklist (PEP 8)
- ✅ snake_case variable and function names
- ✅ Docstrings for modules, functions, and scripts
- ✅ Lines ≤ 79 chars where practical
- ✅ Spaces around operators and after commas (`a + b`, `x, y`)
- ✅ Meaningful names and comments kept concise


## 4. Debugging Log
- **Error Type:** What exception did you hit (e.g., `ValueError`)?
- **Cause:** Why did it happen?
- **Fix:** What change solved it?

**Error Type:** `ValueError`  
**Cause:** Tried converting a non-numeric string ("hello") into an integer.  
**Fix:** Validate input before casting with `.isdigit()`:

```python
num = input("Enter a number: ")
if num.isdigit():
    print(int(num))
else:
    print("Please enter digits only.")

## 5. Reflection (3–5 bullet points)
- Felt confident understanding variables and how Python stores and changes data.  
- Needed extra time on data types and casting, but now I understand why `input()` always returns a string.  
- It was helpful to actually break the code and see what a `ValueError` looks like.  
- Realized that clean formatting (PEP 8) makes code way easier to read.  
- Tomorrow I’ll start Chapter 3 (conditionals) and focus on using `if` statements with real examples.
